sudo: required

language: generic

services:
  - docker

before_install:
  - docker build -t andreyterentyev/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true andreyterentyev/docker-react npm run test
